Fly/Controllers/AreaCController.cs
using Fly.BLL;
using Fly.DomainModel;
using Fly.Resources;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Fly.Controllers
{
    public class AreaCController : AdminBaseController
    {
        public ActionResult Index(int? id)
        {
            ViewBag.ActiveMenu = 1;

            AreasT areaModel = new AreasT();

            if (id != null)
            {
                using (AreasTRepository vehiclesProxy = new AreasTRepository())
                {
                    areaModel = vehiclesProxy.GetById((int)id);
                }

                areaModel.CountriesList = new CountriesRepository().GetAll().ToList();
                return PartialView("_AddArea", areaModel);
            }
            else
            {
                if (Request.IsAjaxRequest())
                {
                    areaModel.CountriesList = new CountriesRepository().GetAll().ToList();
                    return PartialView("_AddArea", areaModel);
                }
                else
                {
                    return View(areaModel);
                }
            }
        }

        public ActionResult loadData(String searchtoken)
        {

            AreasTRepository areaProxy = new AreasTRepository();

            // get start (paging start index) and length (page size for pagging)
            var draw = Request.Form.GetValues("draw").FirstOrDefault();
            var start = Request.Form.GetValues("start").FirstOrDefault();
            var length = Request.Form.GetValues("length").FirstOrDefault();
            // get sort columns value
            var sortColumn =
                Request.Form.GetValues("columns[" + Request.Form.GetValues("order[0][column]").FirstOrDefault() +
                                       "][name]").FirstOrDefault();
            var sortColumnDir = Request.Form.GetValues("order[0][dir]").FirstOrDefault();
            int pageSize = length != null ? Convert.ToInt32(length) : 0;
            int skip = start != null ? Convert.ToInt32(start) : 0;

            var v = areaProxy.get(skip, pageSize, searchtoken, sortColumn, sortColumnDir)
                  .Distinct().ToList();//.OrderBy(sortColumn + " " + sortColumnDir)

            int totalRecords = areaProxy.Getcount(searchtoken);
            var toSerialize = new
            {
                draw = draw,
                recordsFiltered = totalRecords,
                recordsTotal = totalRecords,

                data = v.Select(r => new
                {
                    r.Id,
                    Name= r.Name,
                    CName=r.Countries.Name
                }).AsQueryable()

            };

            var test = Json(
                toSerialize,
                JsonRequestBehavior.AllowGet);
            return test;
        }

        [HttpPost]
        [ValidateInput(false)]
        public ActionResult Add(AreasT model)
        {
            if (model.Id == 0)
            {
                ModelState["Id"].Errors.Clear();
            }

            if (ModelState.IsValid)
            {
                using (AreasTRepository areaProxy = new AreasTRepository())
                {
                    reqResponse = areaProxy.AddUpdate(model);

                    return Json(reqResponse, JsonRequestBehavior.AllowGet);
                }
            }
            else
            {
                reqResponse.ErrorMessages.Add("invalidData", OperationLP.InvalidData);
                return Json(reqResponse, JsonRequestBehavior.AllowGet);
            }
        }

        public ActionResult Delete(int id)
        {
            using (AreasTRepository areaProxy = new AreasTRepository())
            {
                bool isSuccess = areaProxy.Delete(id);
                return Json(new { isSuccess = isSuccess, responseType = isSuccess ? 1 : 2, msg = isSuccess ? OperationLP.DeleteSuccessfully : OperationLP.DeleteFailuer }, JsonRequestBehavior.AllowGet);
            }

        }

    }
}

Fly/Controllers/GlobalCtrlController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Fly.Controllers
{
    public class GlobalCtrlController : AdminBaseController
    {
        // GET: Administration/GlobalCtrl
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult TableStructure(int colmnCount, int operationsColumnCount)
        {
            ViewBag.columnCount = colmnCount;
            ViewBag.columnOperationCount = operationsColumnCount;

            return PartialView("_TableStructure");
        }
    }
}

Fly/Views/AreaC/Index.cshtml
@using Fly.Resources
@{
    ViewBag.Title = "Areas";
    Layout = "~/Views/Shared/_Layout2.cshtml";
}

<div class="row">

    <div class="col-md-12 col-xs-12">
        <div class="panel panel-white">
            <div class="panel-body">

                <div class="row">
                    <div class="col-md-2">
                        <h4 class="panel-title text-primary padding-top-10 text-bold">Vehicles</h4>
                    </div>
                    <div class="col-md-10">
                        <div class="row">

                            <div class="col-md-3">
                            </div>

                            <div class="col-md-3">
                            </div>

                            <div class="col-md-4">
                                <br />
                                <div class="input-group">
                                    <input name="searchToken" id="searchToken" placeholder="@OperationLP.TxtSearch" class="form-control" />

                                    <span class="input-group-btn">
                                        <button type="button" id="search" class="btn btn-success" onclick="search()" data-original-title="@OperationLP.BtnSearch" data-toggle="tooltip">

                                            <span class="fa-search fa"></span>
                                        </button>
                                    </span>
                                </div>

                            </div>

                            <div class="col-md-2">
                                <br />
                                <button type="button" id="addItem" class="btn btn-primary" data-original-title="@OperationLP.BtnNew" data-toggle="tooltip">
                                    @OperationLP.BtnNew
                                    <span class="fa-plus fa"></span>
                                </button>
                            </div>


                        </div>
                    </div>

                </div>


                @Html.Action("TableStructure", "GlobalCtrl", new { area = "", @colmnCount = 2, @operationsColumnCount = 1 })

            </div>
        </div>
    </div>

</div>


@Html.Partial("/Views/Shared/_TableLocalize.cshtml")


<script src="~/Scripts/DevScripts/StandardForm.js"></script>


<script>

    var ActionLoadData = "@Url.Action("loadData")";
    var ActionEditData = "@Url.Action("index", "AreaC")";
    var ActionDeleteData = "@Url.Action("Delete", "AreaC")";

    var colData = [
    { "data": "Name", "title": "Name", "name": "Name", "autoWidth": true, "orderable": true },
    { "data": "CName", "title": "Country", "name": "CName", "autoWidth": true, "orderable": false },
     { "data": "Id", "name": "", "autoWidth": false, "orderable": false }
    ];



    operationIndex = 2;

    GenerateTableCustomColumn();

</script>

<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBLKRh7JfikPylbNdGfTiDbe6zut1yabxo&libraries=drawing,geometry&callback="></script>

Fly/Views/AreaC/_AddArea.cshtml
@model Fly.DomainModel.AreasT

@using (Ajax.BeginForm("Add", "AreaC", new AjaxOptions { OnBegin = "OnBegin", OnComplete = "OnComplete", OnSuccess = "OnSucess" }, new { id = "addForm" }))
{

    <div class="modal-body" style="background-color:#ffffff;">

        @Html.HiddenFor(model => model.Id, new { @class = "EmptyClassID" })
        @Html.HiddenFor(model => model.AreaCoordinates, new { @class = "EmptyClassID", @id = "txtCoordinates" })
        <div class="row">
            <div class="col-md-3">
                <div class="form-group">
                    <label class="text-bold">Name</label>
                    <span class="symbol required" aria-required="true"></span>
                    @Html.TextBoxFor(model => model.Name, new { @class = "form-control EmptyClass" })
                    @Html.ValidationMessageFor(model => model.Name, "", new { @class = "required" })
                </div>
            </div>

            <div class="col-xs-3">
                <div class="form-group">
                    <label for="form-field-select-1" class="text-bold">Country</label>
                    <select class="select2internal" name="CountryId">
                        @foreach (var item in Model.CountriesList)
                        {
                            <option value="@item.Id" @(item.Id == Model.CountryId ? "selected" : "") )>@item.Name</option>
                        }
                    </select>
                    @Html.ValidationMessageFor(m => m.CountryId, "", new { @class = "text-danger" })
                </div>
            </div>

        </div>
        <div class="row">
            <div class="col-xs-12">
                <div id="googleMap" style="height:200px;width:100%;"></div>
            </div>
        </div>

    </div>
    <div class="modal-footer">
        <button type="submit" class="btn btn-success btnSave" id="btnSave">
            Save
        </button>
        <button type="button" class="btn btn-primary btn-o" data-dismiss="modal">
            Close
        </button>
    </div>
}



<script>
    $.validator.unobtrusive.parse("#addForm");
    $(document).ready(function () {
        $(".select2internal").select2();
    });


</script>

<script>
    var currentPoly = "@Model.AreaCoordinates";

    $(document).ready(function () {
        myMap();
    });

    var map;
    var marker;
    var polygonArray;
    var polyObj;
    function myMap() {
        var myCenter = new google.maps.LatLng(30.016164, 31.417952);
        var mapProp = { center: myCenter, zoom: 12, scrollwheel: false, draggable: true, mapTypeId: google.maps.MapTypeId.ROADMAP };
         map = new google.maps.Map(document.getElementById("googleMap"), mapProp);
        var drawingManager = new google.maps.drawing.DrawingManager({
            drawingMode: google.maps.drawing.OverlayType.POLYGON,
            drawingControl: true,
            drawingControlOptions: {
                position: google.maps.ControlPosition.TOP_CENTER,
                drawingModes: ['polygon']
            },
            polylineOptions: {
                editable: true,

            },
            //// markerOptions: { icon: 'https://developers.google.com/maps/documentation/javascript/examples/full/images/beachflag.png' },
            polygonOptions: {
                strokeWeight: 0,
                fillOpacity: 0.45,
                editable: true
            }
        });
        drawingManager.setMap(map);
        google.maps.event.addListener(drawingManager, 'polygoncomplete', function (polygon) {
            $("#txtCoordinates").val('');
            for (var i = 0; i < polygon.getPath().getLength() ; i++) {
                $("#txtCoordinates").val($("#txtCoordinates").val() + polygon.getPath().getAt(i).toUrlValue(6) + "$");
            }
            polygonArray = polygon;//.getPath();
        });


        if (currentPoly != "") {
            polygonArray = [];
            var splitedPathes = currentPoly.split("$").forEach(function (e) {
                if (e != undefined && e != "") {
                    polygonArray.push({ lat: Number(e.split(",")[0]), lng: Number(e.split(",")[1]) });
                }
            })
            // Construct the polygon.
            polyObj = new google.maps.Polygon({
                paths: polygonArray,
                strokeWeight: 0,
                fillOpacity: 0.45,
                editable: true
            });
            polyObj.setMap(map);
        }
    }
</script>