Fly/Controllers/GlobalCtrlController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Fly.Controllers
{
    public class GlobalCtrlController : AdminBaseController
    {
        // GET: Administration/GlobalCtrl
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult TableStructure(int colmnCount, int operationsColumnCount)
        {
            ViewBag.columnCount = colmnCount;
            ViewBag.columnOperationCount = operationsColumnCount;

            return PartialView("_TableStructure");
        }
    }
}

Fly/Controllers/PromoCodeController.cs
using Fly.BLL;
using Fly.DomainModel;
using Fly.Resources;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Fly.Controllers
{
    public class PromoCodeController : AdminBaseController
    {
        public ActionResult Index(int? id)
        {
            ViewBag.ActiveMenu = 1;

            PromoCode areaModel = new PromoCode();

            if (id != null)
            {
                using (PromoCodeRepository vehiclesProxy = new PromoCodeRepository())
                {
                    areaModel = vehiclesProxy.GetById((int)id);
                }

                return PartialView("_AddPromo", areaModel);
            }
            else
            {
                if (Request.IsAjaxRequest())
                {
                    return PartialView("_AddPromo", areaModel);
                }
                else
                {
                    return View(areaModel);
                }
            }
        }

        public ActionResult loadData(String searchtoken)
        {

            PromoCodeRepository areaProxy = new PromoCodeRepository();

            // get start (paging start index) and length (page size for pagging)
            var draw = Request.Form.GetValues("draw").FirstOrDefault();
            var start = Request.Form.GetValues("start").FirstOrDefault();
            var length = Request.Form.GetValues("length").FirstOrDefault();
            // get sort columns value
            var sortColumn =
                Request.Form.GetValues("columns[" + Request.Form.GetValues("order[0][column]").FirstOrDefault() +
                                       "][name]").FirstOrDefault();
            var sortColumnDir = Request.Form.GetValues("order[0][dir]").FirstOrDefault();
            int pageSize = length != null ? Convert.ToInt32(length) : 0;
            int skip = start != null ? Convert.ToInt32(start) : 0;

            var v = areaProxy.get(skip, pageSize, searchtoken, sortColumn, sortColumnDir)
                  .Distinct().ToList();//.OrderBy(sortColumn + " " + sortColumnDir)

            int totalRecords = areaProxy.Getcount(searchtoken);
            var toSerialize = new
            {
                draw = draw,
                recordsFiltered = totalRecords,
                recordsTotal = totalRecords,

                data = v.Select(r => new
                {
                    r.Id,
                    Name = r.Name,
                    Percentage = r.Percentage,
                    IsDelete = r.IsDeleted
                }).AsQueryable()

            };

            var test = Json(
                toSerialize,
                JsonRequestBehavior.AllowGet);
            return test;
        }

        [HttpPost]
        [ValidateInput(false)]
        public ActionResult Add(PromoCode model)
        {
            if (model.Id == 0)
            {
                ModelState["Id"].Errors.Clear();
            }

            if (ModelState.IsValid)
            {
                using (PromoCodeRepository areaProxy = new PromoCodeRepository())
                {
                    reqResponse = areaProxy.AddUpdate(model);

                    return Json(reqResponse, JsonRequestBehavior.AllowGet);
                }
            }
            else
            {
                reqResponse.ErrorMessages.Add("invalidData", OperationLP.InvalidData);
                return Json(reqResponse, JsonRequestBehavior.AllowGet);
            }
        }
    }

}

Fly/Views/PromoCode/Index.cshtml
@using Fly.Resources
@{
    ViewBag.Title = "Promocode";
    Layout = "~/Views/Shared/_Layout2.cshtml";
}


<div class="row">

    <div class="col-md-12 col-xs-12">
        <div class="panel panel-white">
            <div class="panel-body">

                <div class="row">
                    <div class="col-md-2">
                        <h4 class="panel-title text-primary padding-top-10 text-bold">Promocode</h4>
                    </div>
                    <div class="col-md-10">
                        <div class="row">

                            <div class="col-md-3">
                                <div class="form-group">

                                </div>
                            </div>

                            <div class="col-md-3">
                                <div class="form-group">

                                </div>
                            </div>

                            <div class="col-md-4">
                                <br />
                                <div class="input-group">
                                    <input name="searchToken" id="searchToken" placeholder="@OperationLP.TxtSearch" class="form-control" />

                                    <span class="input-group-btn">
                                        <button type="button" id="search" class="btn btn-success" onclick="search()" data-original-title="@OperationLP.BtnSearch" data-toggle="tooltip">

                                            <span class="fa-search fa"></span>
                                        </button>
                                    </span>
                                </div>

                            </div>

                            <div class="col-md-2">
                                <br />
                                <button type="button" id="addItem" class="btn btn-primary" data-original-title="@OperationLP.BtnNew" data-toggle="tooltip">
                                    Add
                                    <span class="fa-plus fa"></span>
                                </button>
                            </div>


                        </div>
                    </div>

                </div>


                @Html.Action("TableStructure", "GlobalCtrl", new { area = "", @colmnCount = 3, @operationsColumnCount = 1 })

            </div>
        </div>
    </div>

</div>


@Html.Partial("/Views/Shared/_TableLocalize.cshtml")


<script src="~/Scripts/DevScripts/StandardForm.js"></script>

<script>

    var ActionLoadData = "@Url.Action("loadData")";
    var ActionEditData = "@Url.Action("index", "PromoCode")";
    var colData = [
    { "data": "Name", "title": "Name", "name": "Name", "autoWidth": true, "orderable": true },
    { "data": "Percentage", "title": "%", "name": "Percentage", "autoWidth": true, "orderable": true },
    { "data": "IsDelete", "title": "Deleted?", "name": "IsDelete", "autoWidth": true, "orderable": true },
     { "data": "Id", "name": "", "autoWidth": false, "orderable": false }
    ];


    deleteEnabled = false;
    isActiveIndex = 2;

    operationIndex = 3;
    GenerateTableCustomColumn();



</script>

Fly/Views/PromoCode/_AddPromo.cshtml
@model Fly.DomainModel.PromoCode

@using (Ajax.BeginForm("Add", "PromoCode", new AjaxOptions { OnBegin = "OnBegin", OnComplete = "OnComplete", OnSuccess = "OnSucess" }, new { id = "addForm" }))
{

    <div class="modal-body" style="background-color:#ffffff;">

        @Html.HiddenFor(model => model.Id, new { @class = "EmptyClassID" })

        <div class="row">
            <div class="col-md-3">
                <div class="form-group">
                    <label class="text-bold">Name</label>
                    <span class="symbol required" aria-required="true"></span>
                    @Html.TextBoxFor(model => model.Name, new { @class = "form-control EmptyClass" })
                    @Html.ValidationMessageFor(model => model.Name, "", new { @class = "required" })
                </div>
            </div>

            <div class="col-xs-3">
                
                <div class="form-group">
                    <label for="form-field-select-1" class="text-bold">Discount %</label>
                    <span class="symbol required" aria-required="true"></span>
                    @Html.TextBoxFor(model => model.Percentage, new { @class = "form-control EmptyClass" })
                    @Html.ValidationMessageFor(m => m.Percentage, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="col-xs-3">
                <br />
                <div class="form-group">
                    <div class="checkbox clip-check check-success checkbox-inline">
                        <input type="checkbox" id="checkbox112" name="IsDeleted" value="true" @(Model != null ? (Model.IsDeleted == true ? "checked" : "") : "")>
                        <label for="checkbox112">
                            Deleted
                        </label>
                    </div>

                </div>
            </div>
        </div>

    </div>
    <div class="modal-footer">
        <button type="submit" class="btn btn-success btnSave" id="btnSave">
            Save
        </button>
        <button type="button" class="btn btn-primary btn-o" data-dismiss="modal">
            Close
        </button>
    </div>
}



<script>
    $.validator.unobtrusive.parse("#addForm");
</script>