Fly/Controllers/GlobalCtrlController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Fly.Controllers
{
    public class GlobalCtrlController : AdminBaseController
    {
        // GET: Administration/GlobalCtrl
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult TableStructure(int colmnCount, int operationsColumnCount)
        {
            ViewBag.columnCount = colmnCount;
            ViewBag.columnOperationCount = operationsColumnCount;

            return PartialView("_TableStructure");
        }
    }
}

Fly/Controllers/VehiclesAController.cs
using Fly.BLL;
using Fly.DomainModel;
using Fly.DomainModel.Helper;
using Fly.Resources;
using RestSharp;
using System;
using System.Collections.Generic;
using System.Drawing;
using System.Drawing.Imaging;
using System.IO;
using System.Linq;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Text;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
//using QRBarcodeService;
using ThoughtWorks.QRCode.Codec;

namespace Fly.Controllers
{
    public class VehiclesAController : AdminBaseController
    {
        //public log4net.ILog logger;
        //public VehiclesAController()
        //{
        //    logger = log4net.LogManager.GetLogger(System.Reflection.MethodBase.GetCurrentMethod().DeclaringType);
        //}

        public ActionResult Image(string imageId)
        {
            //try
            //{
            imageId = WebUI.Helpers.WebUiUtility.Decrypt(imageId);

            QRCodeEncoder qrCodeEncoder = new QRCodeEncoder
            {
                QRCodeEncodeMode = QRCodeEncoder.ENCODE_MODE.BYTE,
                QRCodeScale = 4,
                QRCodeVersion = 8,
                QRCodeErrorCorrect = QRCodeEncoder.ERROR_CORRECTION.H
            };
            Image image = qrCodeEncoder.Encode(imageId);


            using (var ms = new MemoryStream())
            {
                image.Save(ms, ImageFormat.Jpeg);

                image.Dispose();
                return File(ms.ToArray(), "image/jpeg");
            }
            //}
            //catch (Exception ex)
            //{
            //    logger.Error(ex.Message + " > " + ex.InnerException.Message + " > " + ex.StackTrace);
            //    return null;
            //}
        }

        public ActionResult Index(int? id)
        {
            ViewBag.ActiveMenu = 1;

            Vehicles areaModel = new Vehicles();

            if (id != null)
            {
                using (VehicleRepository vehiclesProxy = new VehicleRepository())
                {
                    areaModel = vehiclesProxy.GetById((int)id);
                }

                areaModel.vCategory = new VehiclesCategoryRepository().GetAll().Select(x => new LukUpModel()
                {
                    Id = x.Id,
                    Name = x.Name
                }).ToList();
                areaModel.vBrand = new VehiclesBrandRepositroy().GetAll().Select(x => new LukUpModel()
                {
                    Id = x.Id,
                    Name = x.Name
                }).ToList();
                areaModel.AreasList = new AreasTRepository().GetAll().Select(x => new LukUpModel()
                {
                    Id = x.Id,
                    Name = x.Name,
                    extraValue = x.AreaCoordinates
                }).ToList();
                //areaModel.VehicleSpecs = new VehicleSpecs();

                return PartialView("_AddVehicles", areaModel);
            }
            else
            {
                if (Request.IsAjaxRequest())
                {
                    areaModel = new Vehicles()
                    {
                        vCategory = new VehiclesCategoryRepository().GetAll().Select(x => new LukUpModel()
                        {
                            Id = x.Id,
                            Name = x.Name
                        }).ToList(),
                        vBrand = new VehiclesBrandRepositroy().GetAll().Select(x => new LukUpModel()
                        {
                            Id = x.Id,
                            Name = x.Name
                        }).ToList(),
                        AreasList = new AreasTRepository().GetAll().Select(x => new LukUpModel()
                        {
                            Id = x.Id,
                            Name = x.Name,
                            extraValue = x.AreaCoordinates
                        }).ToList(),
                        VehicleSpecs = new VehicleSpecs(),

                    };
                    return PartialView("_AddVehicles", areaModel);
                }
                else
                {
                    return View(areaModel);
                }
            }
        }

        public ActionResult loadData(String searchtoken)
        {

            VehicleRepository areaProxy = new VehicleRepository();

            // get start (paging start index) and length (page size for pagging)
            var draw = Request.Form.GetValues("draw").FirstOrDefault();
            var start = Request.Form.GetValues("start").FirstOrDefault();
            var length = Request.Form.GetValues("length").FirstOrDefault();
            // get sort columns value
            var sortColumn =
                Request.Form.GetValues("columns[" + Request.Form.GetValues("order[0][column]").FirstOrDefault() +
                                       "][name]").FirstOrDefault();
            var sortColumnDir = Request.Form.GetValues("order[0][dir]").FirstOrDefault();
            int pageSize = length != null ? Convert.ToInt32(length) : 0;
            int skip = start != null ? Convert.ToInt32(start) : 0;

            var v = areaProxy.get(skip, pageSize, searchtoken, sortColumn, sortColumnDir)
                  .Distinct().ToList();//.OrderBy(sortColumn + " " + sortColumnDir)

            int totalRecords = areaProxy.Getcount(searchtoken);
            var toSerialize = new
            {
                draw = draw,
                recordsFiltered = totalRecords,
                recordsTotal = totalRecords,

                data = v.Select(r => new
                {
                    r.Id,
                    VName = r.Name,
                    PlateNo = r.PlateNo,
                    QRCode = r.UniqueId,
                    imageId = WebUI.Helpers.WebUiUtility.Encrypt(r.UniqueId),
                    IsActive = r.IsActive,
                    InRide = r.VehicleStatus.InRide,
                    InService = r.VehicleStatus.InService,
                    BatteryStatus = r.VehicleStatus.BatteryStatus
                }).AsQueryable()

            };

            var test = Json(
                toSerialize,
                JsonRequestBehavior.AllowGet);
            return test;
        }

        [HttpPost]
        [ValidateInput(false)]
        public ActionResult Add(Vehicles model)
        {
            if (model.Id == 0)
            {
                ModelState["Id"].Errors.Clear();
                ModelState["VehicleSpecs.ModelId"].Errors.Clear();
                ModelState["VehicleStatus.VehicleId"].Errors.Clear();
                ModelState["VehicleStatus.BatteryStatus"].Errors.Clear();
                ModelState["VehicleStatus.InRide"].Errors.Clear();
                //ModelState["VehicleStatus.InService"].Errors.Clear();
            }

            if (ModelState.IsValid)
            {
                string fileName = ""; string fileName2 = "";
                foreach (string file in Request.Files)
                {
                    var fileContent = Request.Files[file];
                    if (fileContent != null && fileContent.ContentLength > 0)
                    {
                        fileName = Path.GetFileName(fileContent.FileName);

                        fileName = Guid.NewGuid().ToString().Substring(0, 6).ToString() + fileName;
                        // Add file
                        var path = Path.Combine(Server.MapPath("~/DataImages/"), fileName);
                        fileContent.SaveAs(path);
                    }
                }
                if (!string.IsNullOrEmpty(fileName))
                {
                    model.ImageName = fileName;
                }
                if (!string.IsNullOrEmpty(fileName2))
                {
                    model.UniqueId = fileName2;
                }
                using (VehicleRepository areaProxy = new VehicleRepository())
                {
                    reqResponse = areaProxy.AddUpdate(model);

                    return Json(reqResponse, JsonRequestBehavior.AllowGet);
                }
            }
            else
            {
                reqResponse.ErrorMessages.Add("invalidData", OperationLP.InvalidData);
                return Json(reqResponse, JsonRequestBehavior.AllowGet);
            }
        }

        public ActionResult Delete(int id)
        {
            using (VehicleRepository areaProxy = new VehicleRepository())
            {
                bool isSuccess = areaProxy.Delete(id);
                return Json(new { isSuccess = isSuccess, responseType = isSuccess ? 1 : 2, msg = isSuccess ? OperationLP.DeleteSuccessfully : OperationLP.DeleteFailuer }, JsonRequestBehavior.AllowGet);
            }

        }


        [HttpPost]
        public ActionResult GetBrandModels(int brandId)
        {
            using (VehiclesModelRepository vModelProxy = new VehiclesModelRepository())
            {
                return Json(vModelProxy.GetByBrand(brandId).Select(x => new LukUpModel()
                {
                    Id = x.Id,
                    Name = x.Name
                }));
            }

        }
    }
}

Fly/Views/VehiclesA/Index.cshtml
@using Fly.Resources
@{
    ViewBag.Title = "Vehicles";
    Layout = "~/Views/Shared/_Layout2.cshtml";
}

<div class="row">

    <div class="col-md-12 col-xs-12">
        <div class="panel panel-white">
            <div class="panel-body">

                <div class="row">
                    <div class="col-md-2">
                        <h4 class="panel-title text-primary padding-top-10 text-bold">Vehicles</h4>
                    </div>
                    <div class="col-md-10">
                        <div class="row">

                            <div class="col-md-3">
                                <div class="form-group">
                                    @*Vehicles
                                    <select class="select2">
                                        <option>s</option>
                                        <option>s</option>
                                        <option>s</option>
                                    </select>*@
                                    @*@Html.DropDownList("Pages", new SelectList(new Temp.BLL.PagesLukpRepository().GetAll(), "Id", LayOutLP.CultureUI == "en-GB" ? "NameAr" : "NameEn"), LabelLP.SelectPage, new { @class = "select2", id = "ddlPages1", @style = "width:100%" })*@

                                </div>
                            </div>

                            <div class="col-md-3">
                                <div class="form-group">
                                    @*المكان*@

                                    @*@Html.DropDownList("Position", new SelectList(new Temp.BLL.PagePositionRepository().GetByPageId(222), "Id", LayOutLP.CultureUI == "en-GB" ? "Id" : "Id"), "اختر المكان", new { @class = "select2", id = "ddlPagePostions1", @style = "width:100%" })*@
                                </div>
                            </div>

                            <div class="col-md-4">
                                <br />
                                <div class="input-group">
                                    <input name="searchToken" id="searchToken" placeholder="@OperationLP.TxtSearch" class="form-control" />

                                    <span class="input-group-btn">
                                        <button type="button" id="search" class="btn btn-success" onclick="search()" data-original-title="@OperationLP.BtnSearch" data-toggle="tooltip">

                                            <span class="fa-search fa"></span>
                                        </button>
                                    </span>
                                </div>

                            </div>

                            <div class="col-md-2">
                                <br />
                                <button type="button" id="addItem" class="btn btn-primary" data-original-title="@OperationLP.BtnNew" data-toggle="tooltip">
                                    Add
                                    <span class="fa-plus fa"></span>
                                </button>
                            </div>


                        </div>
                    </div>

                </div>


                @Html.Action("TableStructure", "GlobalCtrl", new { area = "", @colmnCount = 8, @operationsColumnCount = 1 })

            </div>
        </div>
    </div>

</div>


@Html.Partial("/Views/Shared/_TableLocalize.cshtml")


<script src="~/Scripts/DevScripts/StandardForm.js"></script>

<script>
    var ActionLoadData = "@Url.Action("loadData")";
    var ActionEditData = "@Url.Action("index", "VehiclesA")";
    var ActionDeleteData = "@Url.Action("Delete", "VehiclesA")";

    var colData = [
    { "data": "VName", "title": "Name", "name": "VName", "autoWidth": true, "orderable": true },
    { "data": "PlateNo", "title": "Plate", "name": "PlateNo", "autoWidth": true, "orderable": true },
    { "data": "QRCode", "title": "QR", "name": "QRCode", "autoWidth": true, "orderable": true },
    { "data": "BatteryStatus", "title": "Battery", "name": "BatteryStatus", "autoWidth": true, "orderable": true },
    { "data": "IsActive", "title": "Active?", "name": "IsActive", "autoWidth": true, "orderable": true },
    { "data": "InService", "title": "In Service?", "name": "InService", "autoWidth": true, "orderable": true },
    { "data": "InRide", "title": "In Ride?", "name": "InRide", "autoWidth": true, "orderable": true },

    { "data": "imageId", "title": "Print", "name": "imageId", "autoWidth": true, "orderable": false },


     { "data": "Id", "name": "", "autoWidth": false, "orderable": false }
    ];



    operationIndex = 8;
    isActiveIndex = 4;
    isActiveIndex2 = 5;
    isActiveIndex3 = 6;

    isPrint = 7;

    GenerateTableCustomColumn();

    function search() {
        var searchKeyword = document.getElementById('searchToken').value;
        var pageId = $("#ddlPages1 option:selected").val();
        var postionId = $("#ddlPagePostions1 option:selected").val();

        tablesub.ajax.url(ActionLoadData + "?searchtoken=" + searchKeyword + "&pageId=" + pageId + "&positionId=" + postionId);
        tablesub.ajax.reload(null, false);
    }

    function OnBeginWithAttach() {
        $("#addForm").validate();
        var dataString = "";

        var result = true;
        $("#addForm .select222").each(function () {
            try {
                var thisVlaue = $(this).valid();
                if (!$(this).valid()) {
                    result = false;
                }
            } catch (e) {
            }
        });

        if (!result) {
            return false;
        }

        var action = $("#addForm").attr("action");
        if ($("#addForm").attr("enctype") == "multipart/form-data") {
            dataString = new FormData($("#addForm").get(0));

            var files = document.getElementById("mainPic").files;
            for (var x = 0; x < files.length; x++) {
                dataString.append("scoter1", files[x]);
            }

            //files = document.getElementById("traineePic2").files;
            //for (var x = 0; x < files.length; x++) {
            //    dataString.append("file2", files[x]);
            //}

            contentType = false;
            processData = false;
        }


        ShowLoader();
        $.ajax({
            type: "POST",
            url: action,
            data: dataString,
            //  dataType: "json", //change to your own, else read my note above on enabling the JsonValueProviderFactory in MVC
            contentType: contentType,
            processData: processData,
            success: function (data) {
                if (data.responseType == 1) {
                    search("");
                    $("#generalModal").modal("hide");
                }
                Notification(data.responseType, data.ErrorMessegesStr || data.MessegesStr);

                HideLoader();
            },
            error: function (jqXHR, textStatus, errorThrown) {
            }
        });

        return false;

    }

    function GetModelBrand(brandId) {
        $.ajax({
            url: "@Url.Action("GetBrandModels", "VehiclesA",new { area=""})",
            type: 'POST',
            data: {
                brandId: brandId
            },
            dataType: 'json',
            success: onDDLSucess,
            error: onDDLFail
        });
        return false;
    }



    function onDDLSucess(result, userContext, methodName) {
        var select = $('#vModelDDL');

        select.empty().trigger("change");
        // add first option
        var option1 = $('<option></option>').text('Select Model').val('');
        option1.appendTo(select);

        if (!result.ErrorMessage) {
            for (var i = 0; i < result.length; i++) {
                if (selectedModel != undefined && selectedModel != "") {
                    var option = $('<option selected></option>').text(result[i].Name).val(result[i].Id);
                    option.appendTo(select);
                } else {
                    var option = $('<option></option>').text(result[i].Name).val(result[i].Id);
                    option.appendTo(select);
                }
            }
            select.trigger("change");
        }
    }

    function onDDLFail(error, userContext, methodName) {

    }
</script>


<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBLKRh7JfikPylbNdGfTiDbe6zut1yabxo&libraries=drawing,geometry&callback="></script>

Fly/Views/VehiclesA/_AddVehicles.cshtml
@model Fly.DomainModel.Vehicles

@using (Ajax.BeginForm("Add", "VehiclesA", new AjaxOptions { HttpMethod = "post", OnBegin = "OnBeginWithAttach" }, new { id = "addForm", enctype = "multipart/form-data" }))
{

    <div class="modal-body" style="background-color:#ffffff;">

        @Html.HiddenFor(model => model.Id, new { @class = "EmptyClassID" })
        @Html.HiddenFor(model => model.ImageName, new { @class = "EmptyClassID" })
        @Html.HiddenFor(model => model.VehicleSpecs.VehicleId)
        @Html.HiddenFor(model => model.VehicleStatus.VehicleId)
        @*@Html.HiddenFor(model => model.VehicleStatus.InService)*@
        @Html.HiddenFor(model => model.VehicleStatus.InRide)
        @Html.HiddenFor(model => model.VehicleStatus.BatteryStatus)
        @Html.HiddenFor(model => model.VehicleStatus.VehicleQR)
        
        <div class="row">
            <div class="col-md-2">
                <div class="form-group">
                    <label class="text-bold">Name</label>
                    <span class="symbol required" aria-required="true"></span>
                    @Html.TextBoxFor(model => model.Name, new { @class = "form-control EmptyClass" })
                    @Html.ValidationMessageFor(model => model.Name, "", new { @class = "required" })
                </div>
            </div>
            <div class="col-md-2">
                <div class="form-group">
                    <label class="text-bold">Plate No.</label>
                    <span class="symbol required" aria-required="true"></span>
                    @Html.TextBoxFor(model => model.PlateNo, new { @class = "form-control EmptyClass" })
                    @Html.ValidationMessageFor(model => model.PlateNo, "", new { @class = "required" })
                </div>
            </div>

            <div class="col-md-3">
                <div class="form-group">
                    <label class="text-bold">QR No.</label>
                    <span class="symbol required" aria-required="true"></span>
                    @Html.TextBoxFor(model => model.UniqueId, new { @class = "form-control EmptyClass", @readonly = "readonly" })
                </div>
            </div>

            <div class="col-md-2">
                <div class="form-group">
                    <div class="checkbox clip-check check-success checkbox-inline">
                        <input type="checkbox" id="checkbox111" name="IsActive" value="true" @(Model.IsActive ? "checked" : "")>
                        <label for="checkbox111">
                            Active
                        </label>
                    </div>

                </div>


                <div class="form-group">
                    <div class="checkbox clip-check check-success checkbox-inline">
                        <input type="checkbox" id="checkbox112" name="VehicleStatus.InService" value="true" @(Model.VehicleStatus != null ? (Model.VehicleStatus.InService ? "checked" : "") : "")>
                        <label for="checkbox112">
                            Service
                        </label>
                    </div>

                </div>


            </div>

            <div class="col-md-3">
                <div class="form-group">
                    <label class="text-bold">Image</label>
                    <span class="symbol required" aria-required="true"></span>
                    <input type="file" id="mainPic" class="mainInput">
                </div>
            </div>

        </div>

        <div class="row">

            <div class="col-xs-3">
                <div class="form-group">
                    <label for="form-field-select-1" class="text-bold">Category</label>
                    <select class="select2internal" name="VehicleSpecs.CategoryId">
                        @foreach (var item in Model.vCategory)
                        {
                            <option value="@item.Id" @(Model.VehicleSpecs == null ? "" : (item.Id == Model.VehicleSpecs.CategoryId ? "selected" : ""))>@item.Name</option>
                        }
                    </select>
                    @Html.ValidationMessageFor(m => m.VehicleSpecs.CategoryId, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="col-xs-3">
                <div class="form-group">
                    <label for="form-field-select-1" class="text-bold">Brand</label>
                    <select class="select2internal" id="vBrandDDL">
                        <option value="">Select Brand </option>
                        @foreach (var item in Model.vBrand)
                        {
                            <option value="@item.Id" @(Model.VehicleSpecs.VehiclesModel == null ? "" : (item.Id == Model.VehicleSpecs.VehiclesModel.BrandId ? "selected" : ""))>@item.Name</option>
                        }
                    </select>
                </div>
            </div>

            <div class="col-xs-3">
                <div class="form-group">
                    <label for="form-field-select-1" class="text-bold">Model</label>
                    <select class="select2internal" id="vModelDDL" name="VehicleSpecs.ModelId">
                        <option value="">Select Model</option>
                    </select>
                </div>
            </div>

            <div class="col-xs-3">
                <div class="form-group">
                    <label for="form-field-select-1" class="text-bold">Area</label>
                    <select class="select2internal" name="VehicleStatus.AreaId" id="vAreaDDL">
                        <option value="">Select Area</option>
                        @foreach (var item in Model.AreasList)
                        {
                            <option value="@item.Id" data-cord="@item.extraValue" @(Model.VehicleStatus == null ? "" : (item.Id == Model.VehicleStatus.AreaId ? "selected" : ""))>@item.Name</option>
                        }
                    </select>
                </div>
            </div>

        </div>
        <div style="display:none">
            <label>Long</label>
            <input type="text" name="VehicleStatus.LongV" id="longTxt" value="@(Model.VehicleStatus != null ? Model.VehicleStatus.LongV: "")" />
            <br />
            <label>Lat</label>
            <input type="text" name="VehicleStatus.LatV" id="latTxt" value="@(Model.VehicleStatus != null ? Model.VehicleStatus.LatV : "" )" />
        </div>

        <div class="row">
            <div class="col-xs-12">
                <div id="googleMap" style="height:400px;width:100%;"></div>
            </div>
        </div>

    </div>
    <div class="modal-footer">
        <button type="submit" class="btn btn-success btnSave" id="btnSave">
            Save
        </button>
        <button type="button" class="btn btn-primary btn-o" data-dismiss="modal">
            Close
        </button>
    </div>
}

<script>
    var selectedModel = "@(Model.VehicleSpecs.VehiclesModel != null ? Model.VehicleSpecs.VehiclesModel.BrandId.ToString() : "")";
    var lngServer = "@(Model.VehicleStatus != null ? Model.VehicleStatus.LongV :"")";
    var latServer = "@(Model.VehicleStatus != null ? Model.VehicleStatus.LatV :"")";

    $.validator.unobtrusive.parse("#addForm");
    $(document).ready(function () {
        $(".select2internal").select2();

        if ($("#vBrandDDL option:selected").val() > 0) {
            GetModelBrand($("#vBrandDDL option:selected").val());
        }


        $("#vBrandDDL").on("select2:select",
                function (evt) {
                    if ($("#vBrandDDL option:selected").val() > 0) {
                        GetModelBrand($("#vBrandDDL option:selected").val());
                    }
                });

        $("#vAreaDDL").on("select2:select",
                function (evt) {
                    if ($("#vAreaDDL option:selected").val() > 0) {
                        //alert($("#vAreaDDL option:selected").attr("data-cord"));
                    }
                });

    });


</script>
<script>
    var zoomVar = 10;
    var map;
    var marker;
    var polygonArray;

    $(document).ready(function () {
        myMap();
    });
  
    function myMap() {
        if (latServer != "" && lngServer != "") {
            console.log("w")
            var me = new google.maps.LatLng(latServer, lngServer);
            var myCenter = new google.maps.LatLng(latServer, lngServer);//new google.maps.LatLng(20.296100, 85.824500);
            var mapProp = {
                polylineOptions: {
                    editable: true
                }, center: myCenter, zoom: zoomVar, scrollwheel: false, draggable: true, mapTypeId: google.maps.MapTypeId.ROADMAP
            };
            map = new google.maps.Map(document.getElementById("googleMap"), mapProp);
            marker = new google.maps.Marker({ position: myCenter, draggable: true });

            marker.setMap(map);

            google.maps.event.addListener(marker, 'dragend', function (event) {
                document.getElementById("latTxt").value = event.latLng.lat();
                document.getElementById("longTxt").value = event.latLng.lng();
            });

            google.maps.event.addListener(map, 'click', function (event) {
                addMarker(event.latLng);
            });
        } else {
            if (navigator.geolocation) navigator.geolocation.getCurrentPosition(function (pos) {
                console.log("D")
                var me = new google.maps.LatLng(pos.coords.latitude, pos.coords.longitude);

                var myCenter = new google.maps.LatLng(pos.coords.latitude, pos.coords.longitude);//new google.maps.LatLng(20.296100, 85.824500);
                var mapProp = {
                    polylineOptions: {
                        editable: true
                    }, center: myCenter, zoom: zoomVar, scrollwheel: false, draggable: true, mapTypeId: google.maps.MapTypeId.ROADMAP
                };
                map = new google.maps.Map(document.getElementById("googleMap"), mapProp);
                marker = new google.maps.Marker({ position: myCenter, draggable: true });
                marker.setMap(map);


                google.maps.event.addListener(marker, 'dragend', function (event) {
                    document.getElementById("latTxt").value = event.latLng.lat();
                    document.getElementById("longTxt").value = event.latLng.lng();
                });

                google.maps.event.addListener(map, 'click', function (event) {
                    addMarker(event.latLng);
                });
            }, function (error) {
                console.log("e")
                var myCenter = new google.maps.LatLng(30.00982998556293, 31.275490710742588);
                var mapProp = { center: myCenter, zoom: zoomVar, scrollwheel: false, draggable: true, mapTypeId: google.maps.MapTypeId.ROADMAP };
                var map = new google.maps.Map(document.getElementById("googleMap"), mapProp);
                marker = new google.maps.Marker({ position: myCenter, draggable: true });
                marker.setMap(map);

                //google.maps.event.addListener(map, 'bounds_changed', function () {
                //    bounds = map.getBounds();
                //    ne = bounds.getNorthEast();
                //    sw = bounds.getSouthWest();
                //    document.getElementById('mapBounds').innerHTML = bounds.toUrlValue(6);
                //});


                google.maps.event.addListener(marker, 'dragend', function (event) {
                    document.getElementById("latTxt").value = event.latLng.lat();
                    document.getElementById("longTxt").value = event.latLng.lng();
                });

                google.maps.event.addListener(map, 'click', function (event) {
                    addMarker(event.latLng);
                });
            });
        }

    }


    function addMarker(location) {
        document.getElementById("latTxt").value = location.lat();
        document.getElementById("longTxt").value = location.lng();

        if (!marker || !marker.setPosition) {
            marker = new google.maps.Marker({
                position: location,
                map: map,
                draggable: true
            });
        } else {
            marker.setPosition(location);
        }
    }

</script>